import {
  Catalog,
  Dict,
} from './poReader.js';
import {
  LOCALES,
  LocaleDef,
  HEBREW_LOCALE,
  NONIKUD_LOCALE,
  allLocaleNames,
} from './localeMap.js';
import {stripNikud} from './nikud.js';

/** An npm package the catalogue was generated from, for the file header. */
export interface PackageSource {
  pkg: string;
  version: string;
}

/**
 * The "Code generated" banner placed atop every emitted file. When the source
 * npm packages are known, their exact versions are recorded so the generated
 * catalogue is traceable to a reproducible set of inputs.
 */
function makeHeader(sources?: PackageSource[]): string {
  const lines = ['// Code generated by @hebcal/po2catalog. DO NOT EDIT.', '//'];
  if (sources && sources.length > 0) {
    lines.push('// Source of truth is the .po files in these npm packages:');
    for (const s of sources) lines.push(`//   ${s.pkg}@${s.version}`);
  } else {
    lines.push('// Source of truth is the Hebcal .po translation files.');
  }
  lines.push('//', '// Regenerate with: npm run generate');
  return lines.join('\n');
}

/** Quote a string as a Go double-quoted literal (UTF-8 passes through). */
export function goQuote(s: string): string {
  let out = '"';
  for (const ch of s) {
    switch (ch) {
      case '\\': out += '\\\\'; break;
      case '"': out += '\\"'; break;
      case '\n': out += '\\n'; break;
      case '\r': out += '\\r'; break;
      case '\t': out += '\\t'; break;
      default: out += ch;
    }
  }
  return out + '"';
}

/** Go identifier fragment for a locale name: he-x-NoNikud -> he_x_NoNikud. */
function tagVar(name: string): string {
  return 'tag_' + name.replace(/[^A-Za-z0-9]/g, '_');
}

/** Filename stem for a locale's strings file: he-x-NoNikud -> strings_he_x_NoNikud.go. */
function stringsFileName(name: string): string {
  return 'strings_' + name.replace(/[^A-Za-z0-9]/g, '_') + '.go';
}

/**
 * Produce the final per-locale dictionaries, including the baked he-x-NoNikud
 * variant: start from the full he dictionary with niqqud stripped, then layer
 * the explicit he-x-NoNikud.po overrides on top. The catalogue is thus
 * self-contained — no runtime niqqud stripping is required.
 */
export function bakeDictionaries(catalog: Catalog): Map<string, Dict> {
  const result = new Map<string, Dict>();
  for (const def of LOCALES) {
    result.set(def.name, new Map(catalog.get(def.name) ?? []));
  }

  const he = result.get(HEBREW_LOCALE);
  if (he) {
    const baked: Dict = new Map();
    for (const [key, val] of he) {
      const stripped = stripNikud(val);
      if (stripped !== key) baked.set(key, stripped);
    }
    // Explicit NoNikud overrides win over the auto-stripped values.
    for (const [key, val] of result.get(NONIKUD_LOCALE) ?? []) {
      baked.set(key, val);
    }
    result.set(NONIKUD_LOCALE, baked);
  }

  return result;
}

/** Emit one strings_<locale>.go file registering that locale's entries. */
function emitStringsFile(header: string, pkg: string, def: LocaleDef, dict: Dict): string {
  const keys = [...dict.keys()].sort((a, b) => a.localeCompare(b));
  const lines = [
    header,
    '',
    `package ${pkg}`,
    '',
    `// Translations for ${def.name} (${dict.size} entries) -> tag ${def.tag}`,
    `func init() {`,
  ];
  for (const key of keys) {
    lines.push(`\tCatalog.SetString(${tagVar(def.name)}, ${goQuote(key)}, ${goQuote(dict.get(key)!)})`);
  }
  lines.push('}', '');
  return lines.join('\n');
}

/** Emit catalog.go with the builder, tag vars, AllLocales and LookupTranslation. */
function emitCatalogFile(header: string, pkg: string): string {
  const tagDecls = LOCALES.map(
    (d) => `\t${tagVar(d.name)} = language.MustParse(${goQuote(d.tag)})`,
  ).join('\n');

  const localeTagEntries = LOCALES.map(
    (d) => `\t${goQuote(d.name.toLowerCase())}: ${tagVar(d.name)},`,
  ).join('\n');

  const allLocales = allLocaleNames()
    .map((n) => `\t${goQuote(n)},`)
    .join('\n');

  return `${header}

package ${pkg}

import (
\t"strings"
\t"sync"

\t"golang.org/x/text/language"
\t"golang.org/x/text/message"
\t"golang.org/x/text/message/catalog"
)

// Catalog holds every Hebcal translation, keyed by BCP-47 language.Tag.
var Catalog = catalog.NewBuilder()

// Per-locale tags. Non-standard Hebcal locales use private-use subtags so they
// round-trip cleanly through golang.org/x/text/language.
var (
${tagDecls}
)

// localeTags maps a lowercased Hebcal locale name to its catalogue tag.
var localeTags = map[string]language.Tag{
${localeTagEntries}
}

// AllLocales lists every supported Hebcal locale name, in priority order.
var AllLocales = []string{
${allLocales}
}

var (
\tprinterOnce sync.Once
\tprinters    map[string]*message.Printer
)

func getPrinter(locale string) (*message.Printer, bool) {
\tprinterOnce.Do(func() {
\t\tprinters = make(map[string]*message.Printer, len(localeTags))
\t\tfor name, tag := range localeTags {
\t\t\tprinters[name] = message.NewPrinter(tag, message.Catalog(Catalog))
\t\t}
\t})
\tp, ok := printers[locale]
\treturn p, ok
}

// LookupTranslation returns the translated message for key in the given locale.
// It returns ok=false when no translation exists (the key is returned as-is).
//
// "sephardic" and "" are aliases for the "en" locale. For dictionary locales,
// the catalogue never stores identity translations, so a Sprintf result equal
// to the key reliably means "not found".
func LookupTranslation(key string, locale string) (string, bool) {
\tlang := strings.ToLower(locale)
\tswitch lang {
\tcase "", "sephardic":
\t\tlang = "en"
\t}
\tp, ok := getPrinter(lang)
\tif !ok {
\t\treturn key, false
\t}
\ts := p.Sprintf(key)
\tif s == key {
\t\treturn key, false
\t}
\treturn s, true
}
`;
}

/**
 * Emit a generated _test.go that round-trips a sample of entries per locale
 * through LookupTranslation, proving PO -> Go -> catalogue -> printer works.
 */
function emitTestFile(header: string, pkg: string, baked: Map<string, Dict>, samplesPerLocale: number): string {
  const cases: string[] = [];
  for (const def of LOCALES) {
    const dict = baked.get(def.name);
    if (!dict || dict.size === 0) continue;
    const keys = [...dict.keys()].sort((a, b) => a.localeCompare(b)).slice(0, samplesPerLocale);
    for (const key of keys) {
      cases.push(`\t\t{${goQuote(def.name)}, ${goQuote(key)}, ${goQuote(dict.get(key)!)}},`);
    }
  }

  return `${header}

package ${pkg}

import "testing"

func TestLookupTranslation(t *testing.T) {
\tcases := []struct{ locale, key, want string }{
${cases.join('\n')}
\t}
\tfor _, c := range cases {
\t\tgot, ok := LookupTranslation(c.key, c.locale)
\t\tif !ok || got != c.want {
\t\t\tt.Errorf("LookupTranslation(%q, %q) = %q, %v; want %q, true", c.key, c.locale, got, ok, c.want)
\t\t}
\t}
}

func TestPassthroughAndMissing(t *testing.T) {
\tif got, ok := LookupTranslation("Shabbat", "en"); !ok || got != "Shabbat" {
\t\tt.Errorf("en passthrough = %q, %v; want \\"Shabbat\\", true", got, ok)
\t}
\tif got, ok := LookupTranslation("\\u0000 no such key \\u0000", "he"); ok || got != "\\u0000 no such key \\u0000" {
\t\tt.Errorf("missing key = %q, %v; want key, false", got, ok)
\t}
}
`;
}

export interface EmitOptions {
  /** Go package name. */
  pkg: string;
  /** Also emit a self-checking _test.go (and go.mod via the CLI). */
  withTest?: boolean;
  /** Sample entries per locale in the generated test. */
  samplesPerLocale?: number;
  /** Source npm packages + versions, recorded in each file's header. */
  sources?: PackageSource[];
}

/** Generate all Go source files for the given parsed catalogue: filename -> source. */
export function emitGo(catalog: Catalog, opts: EmitOptions): Map<string, string> {
  const baked = bakeDictionaries(catalog);
  const header = makeHeader(opts.sources);
  const files = new Map<string, string>();

  files.set('catalog.go', emitCatalogFile(header, opts.pkg));

  for (const def of LOCALES) {
    const dict = baked.get(def.name) ?? new Map();
    files.set(stringsFileName(def.name), emitStringsFile(header, opts.pkg, def, dict));
  }

  if (opts.withTest) {
    files.set('catalog_generated_test.go', emitTestFile(header, opts.pkg, baked, opts.samplesPerLocale ?? 5));
  }

  return files;
}
