import {
  Catalog,
  Dict,
} from './poReader.js';
import {
  LOCALES,
  LocaleDef,
  HEBREW_LOCALE,
  NONIKUD_LOCALE,
  allLocaleNames,
} from './localeMap.js';
import {stripNikud} from './nikud.js';

const HEADER = `// Code generated by @hebcal/po2catalog. DO NOT EDIT.
//
// Source of truth is the .po files in the Hebcal repos
// (hdate-js, hebcal-es6, hebcal-locales, hebcal-leyning, hebcal-learning).
// Regenerate with: npm run generate`;

/** Quote a string as a Go double-quoted literal (UTF-8 passes through). */
export function goQuote(s: string): string {
  let out = '"';
  for (const ch of s) {
    switch (ch) {
      case '\\': out += '\\\\'; break;
      case '"': out += '\\"'; break;
      case '\n': out += '\\n'; break;
      case '\r': out += '\\r'; break;
      case '\t': out += '\\t'; break;
      default: out += ch;
    }
  }
  return out + '"';
}

/** Go identifier fragment for a locale name: he-x-NoNikud -> he_x_NoNikud. */
function tagVar(name: string): string {
  return 'tag_' + name.replace(/[^A-Za-z0-9]/g, '_');
}

/** Filename stem for a locale's strings file: he-x-NoNikud -> strings_he_x_NoNikud.go. */
function stringsFileName(name: string): string {
  return 'strings_' + name.replace(/[^A-Za-z0-9]/g, '_') + '.go';
}

/**
 * Produce the final per-locale dictionaries, including the baked he-x-NoNikud
 * variant: start from the full he dictionary with niqqud stripped, then layer
 * the explicit he-x-NoNikud.po overrides on top. The catalogue is thus
 * self-contained — no runtime niqqud stripping is required.
 */
export function bakeDictionaries(catalog: Catalog): Map<string, Dict> {
  const result = new Map<string, Dict>();
  for (const def of LOCALES) {
    result.set(def.name, new Map(catalog.get(def.name) ?? []));
  }

  const he = result.get(HEBREW_LOCALE);
  if (he) {
    const baked: Dict = new Map();
    for (const [key, val] of he) {
      const stripped = stripNikud(val);
      if (stripped !== key) baked.set(key, stripped);
    }
    // Explicit NoNikud overrides win over the auto-stripped values.
    for (const [key, val] of result.get(NONIKUD_LOCALE) ?? []) {
      baked.set(key, val);
    }
    result.set(NONIKUD_LOCALE, baked);
  }

  return result;
}

/** Emit one strings_<locale>.go file registering that locale's entries. */
function emitStringsFile(pkg: string, def: LocaleDef, dict: Dict): string {
  const keys = [...dict.keys()].sort((a, b) => a.localeCompare(b));
  const lines = [
    HEADER,
    '',
    `package ${pkg}`,
    '',
    `// Translations for ${def.name} (${dict.size} entries) -> tag ${def.tag}`,
    `func init() {`,
  ];
  for (const key of keys) {
    lines.push(`\tCatalog.SetString(${tagVar(def.name)}, ${goQuote(key)}, ${goQuote(dict.get(key)!)})`);
  }
  lines.push('}', '');
  return lines.join('\n');
}

/**
 * Emit nikud.go exposing the public HebrewStripNikud helper. This is the Go
 * twin of src/nikud.ts (and of hebcal-go's HebrewStripNikkud): the same
 * transform used to bake the he-x-NoNikud catalogue, exported so callers can
 * strip niqqud from arbitrary strings at runtime.
 */
function emitNikudFile(pkg: string): string {
  return `${HEADER}

package ${pkg}

import "strings"

// HebrewStripNikud removes Hebrew niqqud (vowel points) and cantillation marks
// from s. It keeps every rune except those in the Hebrew points/accents block
// U+0590..U+05C7, sparing only U+05BE (MAQAF); note U+05BF (RAFE) is stripped.
// Letters, punctuation and everything outside that block pass through.
//
// This matches hebcal-go's HebrewStripNikkud and is the same transform used to
// bake the he-x-NoNikud dictionary, so stripping a he entry at runtime yields
// the catalogue's he-x-NoNikud value.
func HebrewStripNikud(s string) string {
\tvar b strings.Builder
\tb.Grow(len(s))
\tfor _, r := range s {
\t\tif r < 0x0590 || r > 0x05c7 || r == 0x05be {
\t\t\tb.WriteRune(r)
\t\t}
\t}
\treturn b.String()
}
`;
}

/** Emit catalog.go with the builder, tag vars, AllLocales and LookupTranslation. */
function emitCatalogFile(pkg: string): string {
  const tagDecls = LOCALES.map(
    (d) => `\t${tagVar(d.name)} = language.MustParse(${goQuote(d.tag)})`,
  ).join('\n');

  const localeTagEntries = LOCALES.map(
    (d) => `\t${goQuote(d.name.toLowerCase())}: ${tagVar(d.name)},`,
  ).join('\n');

  const allLocales = allLocaleNames()
    .map((n) => `\t${goQuote(n)},`)
    .join('\n');

  return `${HEADER}

package ${pkg}

import (
\t"strings"
\t"sync"

\t"golang.org/x/text/language"
\t"golang.org/x/text/message"
\t"golang.org/x/text/message/catalog"
)

// Catalog holds every Hebcal translation, keyed by BCP-47 language.Tag.
var Catalog = catalog.NewBuilder()

// Per-locale tags. Non-standard Hebcal locales use private-use subtags so they
// round-trip cleanly through golang.org/x/text/language.
var (
${tagDecls}
)

// localeTags maps a lowercased Hebcal locale name to its catalogue tag.
var localeTags = map[string]language.Tag{
${localeTagEntries}
}

// AllLocales lists every supported Hebcal locale name, in priority order.
var AllLocales = []string{
${allLocales}
}

var (
\tprinterOnce sync.Once
\tprinters    map[string]*message.Printer
)

func getPrinter(locale string) (*message.Printer, bool) {
\tprinterOnce.Do(func() {
\t\tprinters = make(map[string]*message.Printer, len(localeTags))
\t\tfor name, tag := range localeTags {
\t\t\tprinters[name] = message.NewPrinter(tag, message.Catalog(Catalog))
\t\t}
\t})
\tp, ok := printers[locale]
\treturn p, ok
}

// LookupTranslation returns the translated message for key in the given locale.
// It returns ok=false when no translation exists (the key is returned as-is).
//
// "en", "sephardic" and "" are pass-through locales. For dictionary locales,
// the catalogue never stores identity translations, so a Sprintf result equal
// to the key reliably means "not found".
func LookupTranslation(key string, locale string) (string, bool) {
\tlang := strings.ToLower(locale)
\tswitch lang {
\tcase "", "en", "sephardic":
\t\treturn key, true
\t}
\tp, ok := getPrinter(lang)
\tif !ok {
\t\treturn key, false
\t}
\ts := p.Sprintf(key)
\tif s == key {
\t\treturn key, false
\t}
\treturn s, true
}
`;
}

/**
 * Emit a generated _test.go that round-trips a sample of entries per locale
 * through LookupTranslation, proving PO -> Go -> catalogue -> printer works.
 */
function emitTestFile(pkg: string, baked: Map<string, Dict>, samplesPerLocale: number): string {
  const cases: string[] = [];
  for (const def of LOCALES) {
    const dict = baked.get(def.name);
    if (!dict || dict.size === 0) continue;
    const keys = [...dict.keys()].sort((a, b) => a.localeCompare(b)).slice(0, samplesPerLocale);
    for (const key of keys) {
      cases.push(`\t\t{${goQuote(def.name)}, ${goQuote(key)}, ${goQuote(dict.get(key)!)}},`);
    }
  }

  return `${HEADER}

package ${pkg}

import "testing"

func TestLookupTranslation(t *testing.T) {
\tcases := []struct{ locale, key, want string }{
${cases.join('\n')}
\t}
\tfor _, c := range cases {
\t\tgot, ok := LookupTranslation(c.key, c.locale)
\t\tif !ok || got != c.want {
\t\t\tt.Errorf("LookupTranslation(%q, %q) = %q, %v; want %q, true", c.key, c.locale, got, ok, c.want)
\t\t}
\t}
}

func TestPassthroughAndMissing(t *testing.T) {
\tif got, ok := LookupTranslation("Shabbat", "en"); !ok || got != "Shabbat" {
\t\tt.Errorf("en passthrough = %q, %v; want \\"Shabbat\\", true", got, ok)
\t}
\tif got, ok := LookupTranslation("\\u0000 no such key \\u0000", "he"); ok || got != "\\u0000 no such key \\u0000" {
\t\tt.Errorf("missing key = %q, %v; want key, false", got, ok)
\t}
}

func TestHebrewStripNikud(t *testing.T) {
\tcases := []struct{ in, want string }{
\t\t{"\\u05d9\\u05b4\\u05e9\\u05c2\\u05b0\\u05e8\\u05b8\\u05d0\\u05b5\\u05dc", "\\u05d9\\u05e9\\u05e8\\u05d0\\u05dc"}, // israel: niqqud stripped
\t\t{"\\u05d0\\u05beb", "\\u05d0\\u05beb"}, // maqaf (U+05BE) kept
\t\t{"\\u05d0\\u05bf\\u05d1", "\\u05d0\\u05d1"}, // rafe (U+05BF) stripped
\t\t{"Shabbat Shalom", "Shabbat Shalom"}, // non-Hebrew untouched
\t}
\tfor _, c := range cases {
\t\tif got := HebrewStripNikud(c.in); got != c.want {
\t\t\tt.Errorf("HebrewStripNikud(%q) = %q; want %q", c.in, got, c.want)
\t\t}
\t}
}
`;
}

export interface EmitOptions {
  /** Go package name. */
  pkg: string;
  /** Also emit a self-checking _test.go (and go.mod via the CLI). */
  withTest?: boolean;
  /** Sample entries per locale in the generated test. */
  samplesPerLocale?: number;
}

/** Generate all Go source files for the given parsed catalogue: filename -> source. */
export function emitGo(catalog: Catalog, opts: EmitOptions): Map<string, string> {
  const baked = bakeDictionaries(catalog);
  const files = new Map<string, string>();

  files.set('catalog.go', emitCatalogFile(opts.pkg));
  files.set('nikud.go', emitNikudFile(opts.pkg));

  for (const def of LOCALES) {
    const dict = baked.get(def.name) ?? new Map();
    files.set(stringsFileName(def.name), emitStringsFile(opts.pkg, def, dict));
  }

  if (opts.withTest) {
    files.set('catalog_generated_test.go', emitTestFile(opts.pkg, baked, opts.samplesPerLocale ?? 5));
  }

  return files;
}
